[package]
name = "rusty-receipt-proof-maker"
version = "0.1.0"
authors = ["Greg Kapka <greg@oraclize.it>"]
edition = "2018"

[dependencies]
hex = "0.3.2"
serde = "1.0.97"
dotenv = "0.14.1"
reqwest = "0.9.19"
serde_json = "1.0.40"
ethereum-types = "0.6.0"
